### ISSUE TITLE
appShiny : pouvoir comparer plusieurs jeux de données 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#101]
pouvoir comparer plusieurs (en utilisant l’argument compare des modules )  : 

- [x] 1. années monteCartlo de la même études 
- [x] 3. données d'areas, links, clusters et districts
- [x] 5. plusieurs études provenant d'études TXT et/ou de fichiers HDF5

**Comment by bthieurmel** [comment]
You can test last develop version.

**Comment by jalazawa** [comment]
OK
