### ISSUE TITLE
appShiny : feature : add a button OK or deconnection

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#106]
Like this module 

![add_bouton_ok](https://user-images.githubusercontent.com/22026724/31890546-d0850910-b803-11e7-9e2f-052e103c0509.png)

antaresViz app must have a button Ok or Deconnection 

![add_bouton_ok_deconnexion](https://user-images.githubusercontent.com/22026724/31890559-d8e14326-b803-11e7-965e-aca579d1ee66.png)

**Comment by bthieurmel** [comment]
Done with ca77112

**Comment by jalazawa** [comment]
OK
