### ISSUE TITLE
appShiny : feature : print Error and Warning messages of antaresRead directly in the app

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#108]
error messages in RStudio 

![res_message_error](https://user-images.githubusercontent.com/22026724/31892509-7ada15e0-b809-11e7-982d-d3915023f4f1.png)

antaresRead (app) 

![message_error](https://user-images.githubusercontent.com/22026724/31892520-852ce96e-b809-11e7-9309-c39a4a60cc49.png)

**Comment by jalazawa** [comment]
Actuellement, si l'utilisateur fait une erreur dans la sélection des arguments alors l'application se fige et l'erreur est envoyé sur RStudio (non dispo à l'utilisateur sur l'application). 

L'utilisateur doit alors arrêter lui même le process sur RStudio.

**Comment by bthieurmel** [comment]
Add control on 5cfe729. So now a popup is open in case of warning / error

**Comment by jalazawa** [comment]
It's ok in almost all cases but in one case the "error popup" does not appear : 

areas=all and linkCapacity=TRUE 

app 

![error_readantares](https://user-images.githubusercontent.com/22026724/32216151-82353d58-be24-11e7-8218-e779e32fedb6.png)

R console 


```R 
 myData<-readAntares(areas = "all", linkCapacity = TRUE)
Error in readAntares(areas = "all", linkCapacity = TRUE) : 
  When 'linkCapacity' is TRUE, argument 'links' needs to be specified.


````

**Comment by bthieurmel** [comment]
It's because I had a control in the shiny app : 

``
linkCapacity = if(!is.null(input$read_links)) input$read_linkCapacity else FALSE
``

Do you want to remove this control, and so get back the error ?

**Comment by jalazawa** [comment]
Yes, you can remove it. Thanks.

**Comment by bthieurmel** [comment]
Ok. Done.
