### ISSUE TITLE
appShiny : feature : première connexion 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#112]
On pourrait représenter un autre message lors de la première connexion, au lieu de 

"No antares output found in directory" 

L'utilisateur n'a pas encore sélectionné de dossier. 
![first_message](https://user-images.githubusercontent.com/22026724/31894279-3c126b5a-b80e-11e7-8455-a8f4f1a879b9.png)

**Comment by bthieurmel** [comment]
Done. See de81a82

**Comment by jalazawa** [comment]
OK
