### ISSUE TITLE
plot, prodStack and exchangesStack : bug : parameter : interactive = FALSE

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#114]
L'utilisation du paramètre interactive crée une erreur si on utilise une liste de myData (antaresData). 

Il fonctionne très bien pour un élément myData. 

--> L'utilisation du paramètre interactive=FALSE peut-être tester automatiquement ! 

TEST à rajoute 

code OK 

```R
> plot(myData, interactive=FALSE, element="a")
```

code KO 

```R
> plot(list(myData, myData2, myData3), interactive=FALSE, element="a")
Error in params$x[[table]][[table]]$plotFun(mcYear, 1, variable, elements,  : 
  attempt to apply non-function
```

**Comment by jalazawa** [comment]
J'ai aussi un bug pour prodStack quand j'utilise ce paramètre mais il est différent. 

quand j'utilise ces 2 lignes de code, j'obtiens le même résultat, c'est à dire à un graphique alors que dans le deuxième cas je m'attends à avoir 3 graphiques. 

```R 
prodStack(list(myData), interactive=FALSE, areas="b",stack="thermalFirst")
prodStack(list(myData, myData2, myData3), interactive=FALSE, areas="b",stack="thermalFirst")

```

Lorsque je mets le paramètre interactive = TRUE avec une liste d'AntaresData alors j'obtiens bien une application avec 3 graphiques. 

prodStack(list(myData, myData2, myData3), interactive=TRUE, areas="b",stack="thermalFirst")

![prodstack_interactive_true](https://user-images.githubusercontent.com/22026724/31931280-fc35bd1c-b8a2-11e7-9bf4-d536fda48682.png)

**Comment by jalazawa** [comment]
bug avec exchangesStack aussi, le même que prodStack

**Comment by TitouanRobert** [comment]
Ajout de messages d'erreurs quand l'utilisateur donne plusieurs études ou un compare en mode non interactif.

**Comment by jalazawa** [comment]
ok
