### ISSUE TITLE
plot, prodStack and exchangesStack : bug : parameter : mcYear 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#115]
Le paramètre n'est pas vérifié actuellement 

Avec interactive=FALSE, on pourrait rajouter des tests automatiques pour éviter ce bug dans le futur. 

```R
plot(myData, interactive=FALSE, element="a", variable = "LOAD", mcYear="DFEZDFEZ")
```

**Comment by jalazawa** [comment]
pareil pour prodStack

**Comment by jalazawa** [comment]
mcYear 4343434 pour exchangesStack

exchangesStack(myData, interactive=FALSE, area = "b", mcYear=4343434)

**Comment by TitouanRobert** [comment]
Le comportement exact est : quand on donne des données mc-all et que l'on spécifie mcYear, mcYear es ignoré. J'ai donc ajouté un warning : 
You have average data and you specify a mcYear. This specification will be ignore.

**Comment by jalazawa** [comment]
KO pour plot 

Je m'attends à une erreur pour la deuxième ligne 

Peut-on rajouter des tests automatique dans la partie testthat ? 

```R 
plot(myDataDetail3, interactive=FALSE, element="a", variable = "LOAD", mcYear=2)
plot(myDataDetail3, interactive=FALSE, element="a", variable = "LOAD", mcYear=2699)
```

KO pour prodStack aussi avec des données sans mcYear

```R 
prodStack(myData, interactive=FALSE, areas="b",stack="thermalFirst", mcYear="FRER")
```

AUTRE QUESTION : 

Peut-on factoriser le code de vérification des paramètres des différentes fonctions ? 

Ex : verify_antaresData ? verify_antaresDataList ? verify_parameter ? verify_compare ? verify_mcYear ? etc ? afin d'avoir moins de code à maintenir. 

KO pour exchangesStack avec des données sans mcYear

```R 
exchangesStack(myData, interactive=FALSE, area = "b", mcYear=4343434)
```

**Comment by TitouanRobert** [comment]
Fait, par compte ça ne fonctionne pas toujours avec interactive = TRUE (l'affichage du warning). Après je ne pense pas que ce soit un soucis

**Comment by jalazawa** [comment]
Un comportement non homogène quand on rendre des données détaillés et que l'année n'est pas dans le scope. 

Ces 3 fonctions renvoient comme résultat "No Data" 

```R 
plot(myDataDetail3, interactive=FALSE, element="a", variable = "LOAD", mcYear="DFEZDFEZ")

exchangesStack(myDataDetail3, interactive=FALSE, area = "b", mcYear=4343434)

rodStack(myDataDetail3, interactive=FALSE, areas="b",stack="thermalFirst", mcYear=849848)

```

Mais cette fonction renvoie un graphique 


```R 
plotMap(myDataDetail3, ml, interactive = FALSE, mcYear = 23323)

```


Comme on est dans un mode interactive=FALSE, peut-on rajouter des tests automatiques quand mcYear est égal à une valeur aberrante et que la donnée rentrée est un antaresDataList contenant (un ou) plusieurs mcYear ?

**Comment by jalazawa** [comment]
OK
