### ISSUE TITLE
prodStack : parameter : compare 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#116]
Ce n'est peut-être pas un bug mais un manque d'information renvoyée à l'utilisateur.

Si j'utilise le paramètre compare avec une liste d'antaresData alors j'obtiens un shiny gadget avec seulement 2 widgets, je m'attends à avoir autant de widget que d'antaresData dans ma liste. 

```R 
prodStack(list(myData, myData2, myData3), interactive=TRUE, areas="b",stack="thermalFirst", compare = "areas")
prodStack(list(myData, myData2, myData3), interactive=TRUE, areas="b",stack="thermalFirst")

```

La première ligne renvoie une application avec 2 widgets. 

La deuxième ligne renvoie une application avec 3 widgets.

**Comment by jalazawa** [comment]
C'est peut-être le comportement correct du paramètre compare. 

Mais dans le deuxième cas, on devrait me renvoyer une erreur en m'indiquant que le paramètre compare ne fonctionne que pour un jeu de donnée et pas une liste. 

même chose pour la fonction 

exchangesStack(list(myData, myData2, myData3), interactive=TRUE, area = "b", compare="area"
    )

**Comment by TitouanRobert** [comment]
Terminé

**Comment by jalazawa** [comment]
OK
