### ISSUE TITLE
h5 : plot, prodStack, exchange et plotMap : permettre l'utilisation du paramètre interactive =  FALSE 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#124]
Intérêt  

- Permettre à l'utilisateur de générer des rapports automatiques en utilisant le formation h5 (actuellement, il fait un readAntares sur une étude TXT) 
- Permettre de rajouter des tests automatiques sur la visualisation en utilisant les requetes h5 en mode non interactif.

**Comment by TitouanRobert** [comment]
Fait

**Comment by jalazawa** [comment]
OK
