### ISSUE TITLE
appShiny : h5 : année récupérée avec un module mais pas disponible pour les autres modules 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#125]
Je récupère l'année 30 dans le module prodStack. 

cf. image 

![annee_dispo_pour_un_module](https://user-images.githubusercontent.com/22026724/32052677-51ac1748-ba59-11e7-8a04-459417bd2d18.png)

Mais je n'arrive pas à la sélectionner dans les autres modules. 

Je dois encore l'importer ? 

cf. images

![pas_les_autres](https://user-images.githubusercontent.com/22026724/32052734-6ff33ea2-ba59-11e7-8026-e1bc4b4f38fe.png)

![pas_les_autres_2](https://user-images.githubusercontent.com/22026724/32052738-7193ca92-ba59-11e7-821c-84247a32ebbf.png)

**Comment by bthieurmel** [comment]
Actuellement, l'importation des données h5 est faire au niveau de chaque module, et donc non mutualisée entre les modules. On partage cependant les inputs.

- si on a pas de bouton d'update et d'isolation, cela est bon
- sinon, il faut à minima  cliquer sur le bouton

**Comment by jalazawa** [comment]
OK :-)
