### ISSUE TITLE
appShiny : rajouter une section "removeVirtualAreas" 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#128]
Pour l'instant, l'utilisateur peut importer une étude TXT via l'appel de readAntares. 

Malheureusement, ces données ne sont pas nettoyées des nœuds virtuels. 

![add_section](https://user-images.githubusercontent.com/22026724/32054421-a07913c6-ba5e-11e7-9071-f26f9d9f8c1c.png)

Il faudrait rajouter une section "removeVirtualAreas parameters" et récupérer les données nettoyées, un peu comme writeAntaresH5 qui appel à la fois readAntares et removeVirtualAreas. Dans l'aide de cette dernière fonction on fait référence à ces deux fonctions.

**Comment by bthieurmel** [comment]
Done. With same error / warning system.

**Comment by jalazawa** [comment]
KO ! 

When I click at "Launch Analysis" then I get this error even if I build antaresRead - develop. 

```R 
Warning in readAntares(areas = input$read_areas, links = input$read_links,  :
  When misc, hydroStorageMaxPower, reserve or linkCapacity is not null, 'readAntares' reads input time series. Result may be wrong if these time series have changed since the simulation has been run.
Warning: Error in readLayout: Invalid opts argument. Must be a simOptions or a list of simOptions
Stack trace (innermost first):
    89: readLayout [D:/Users/jalazawa/Documents/Dev/PackagesR/develop/github/antaresRead/R/readLayout.R#58]
    82: isolate
    81: <reactive:layout> [src/server/06_module_map.R#4]
    70: layout
    69: <reactive> [D:/Users/jalazawa/Documents/Dev/PackagesR/develop/github/antaresViz/R/map_layout.R#149]
    58: data
    57: observerFunc [D:/Users/jalazawa/Documents/Dev/PackagesR/develop/github/antaresViz/R/map_layout.R#176]
     2: shiny::runApp
     1: runAppAntaresViz [D:/Users/jalazawa/Documents/Dev/PackagesR/develop/github/antaresViz/R/runApp.R#11]
ERROR: [on_request_read] connection reset by peer

```

Try 

![error_simoptions](https://user-images.githubusercontent.com/22026724/32454251-f60815b2-c31e-11e7-939d-8809168f75ad.png)

**Comment by bthieurmel** [comment]
So two solution : 

- we can merge develop branch of antaresRead with next-release before submission
- or I've to find a temporary solution for antaresViz....

**Comment by bthieurmel** [comment]
Add antaresRead version control

**Comment by jalazawa** [comment]
OK
