### ISSUE TITLE
plot : rendre ces différentes paramètres comme une liste 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#134]
But : pouvoir représenter sur le même graphique  wind_fr_mcYear01 et wind_fr_mcYear02
mais aussi wind_fr_mcYear01 et link_de_fr_mcYear01

- [x] mcYear 

- [ ] table

**Comment by jalazawa** [comment]
supprimer average des options pour mcYear pour plot, prodStack, etc.

**Comment by bthieurmel** [comment]
Ok pour les mcYear. Avec correction de quelques autres bugs au passage (couleurs si une série, intervalle de confiance pour les monotones).

Et du coup tu peux maintenant sois avoir le détails pour chaque mcYear, soit faire un intervalle de confiance

**Comment by bthieurmel** [comment]
Trop long/sensible pour la modification niveau table par contre. Donc peut-être plutôt pour la ``0.14``...?

**Comment by jalazawa** [comment]
Je ne comprends pas comment sont gérés les axes Y. 

L'axe Y à gauche contient des coefficients de 0 à 1. 

Est-ce que l'axe Y à droite ne devrait pas être à gauche ? 

OK pour mettre les table dans la 0.14

**Comment by bthieurmel** [comment]
Corrigé. J'ai simplifié au passage l'axe des axes (je pense que le nom des colonnes suffisent, pas besoin d'avoir en plus area __ mcY__, qu'on retrouve dans la légende).

**Comment by jalazawa** [comment]
Yes.
