### ISSUE TITLE
plot : dygraph : option stepPlot, drawPoints, highLight and dyRangeSelector 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#135]
On pourrait utiliser le paramètre stepPlot 

![stepplot](https://user-images.githubusercontent.com/22026724/32214096-0083a5c0-be1e-11e7-8416-d0fbffec161f.png)

Pour toutes les courbes représenter. 

Comme pour la charte graphique, on pourrait spécifier si une courbe utilise cette information. 

cf . [GraphicalCharter AntaresViz](https://github.com/rte-antares-rpackage/antaresViz/blob/master/inst/GraphicalCharter.csv)

L'utilisateur pourra toujours redéfinir cette option comme il peut redéfinir les couleurs. 

stepPlot est disponible dans dans le package R 

cf. demo [dygraphs ](https://rstudio.github.io/dygraphs/gallery-series-options.html)

**Comment by TitouanRobert** [comment]
Traité dans une autre issue
