### ISSUE TITLE
prodStack et exchangesStack : plus d'options 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#136]
lié à #56 

On pourrait aussi utiliser les options drawPoints, highLight, stepPlot et dyRangeSelector.

**Comment by TitouanRobert** [comment]
Pour prodStack et exchangesStack cette option ne rend pas un bon résultat visuel (à cause de l'empilement de graphiques)

**Comment by jalazawa** [comment]
OK
