### ISSUE TITLE
appShiny : initialisation du paramètre mcYear dans les modules 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#140]
Si j'importe plusieurs années via une requête H5 alors je retrouve bien ces années dans les choix possibles dans le champs mcYear. 

cf. image 
![init_mcyear](https://user-images.githubusercontent.com/22026724/32555542-53a26ebe-c49d-11e7-91d9-ecddd563e5d7.png)

Sauf que quand je clic sur un autre module, je constate que j'ai accès seulement à la première année. 

ET quand je reviens au module initiale, je constate que les années importées en question ne sont plus disponible dans le champ mcYear

![init_mcyear_2](https://user-images.githubusercontent.com/22026724/32555601-86ea8d2e-c49d-11e7-84af-f02425f2d9e1.png)

**Comment by bthieurmel** [comment]
Done. But we've to remember we have to click on update button to have a new graphs when we arrive on a panel

**Comment by jalazawa** [comment]
OK !
