### ISSUE TITLE
appShiny : pouvoir changer la limite des graphiques chargés via limitSizeGraph

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#141]
Quand je charge un peu trop de donnée, j'ai ce message 

```R 
To mutch data, please reduce selection. If you work with hourly data, you can reduce dateRange selection. You can also use limitSizeGraph function to remove limit of size.

```

Pourrait-on depuis l'application appeler limitSizeGraph et changer la limite des données chargées dans le graphique ?

**Comment by bthieurmel** [comment]
Add a new panel in shiny

**Comment by jalazawa** [comment]
If I set in "readAntares RAM limit (in Go)" 1 giga and I set 14 Mc year in a request, I get a wrong error message 

![pb_limit_1giga_14mcyear](https://user-images.githubusercontent.com/22026724/32769462-4416c8c2-c91c-11e7-9d65-dd2cc30811d0.png)


If I change readAntares limit from 1 to 10, I get this 

![pb_limit_10giga_14mcyear](https://user-images.githubusercontent.com/22026724/32769469-47939962-c91c-11e7-9dfd-c3ae97c8d108.png)

**Comment by jalazawa** [comment]
OK
