### ISSUE TITLE
prodStack and exchangesStack :  annual data

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#143]
for data daily, we have this 

![data_daily](https://user-images.githubusercontent.com/22026724/32895149-63a61d54-cadf-11e7-988c-94904502428d.png)

for data montly, we have this 

![data_montly](https://user-images.githubusercontent.com/22026724/32895156-6a4653d6-cadf-11e7-9564-db5db606fcda.png)

for data annual, we get this 

![data_annual](https://user-images.githubusercontent.com/22026724/32895168-712c7900-cadf-11e7-9dfa-630999022244.png)

BUT a correct plot for annual data will be something like this 

![res_ref](https://user-images.githubusercontent.com/22026724/32895207-90ed9e04-cadf-11e7-93cf-a119522fba11.png)

for plot, we get already barplot and it's ok. 

We must have the same feature for prodStack and exchangeStack ...

**Comment by jalazawa** [comment]
@bthieurmel  for annual data, we can use this for prodStack (like in the bpNum), barplot or pieChart, it's the same info

![prodstack](https://user-images.githubusercontent.com/22026724/38298458-addb0b34-37f7-11e8-935a-fc7249f66aa5.png)

for exchangeStack, we can use a barplot, two bar : export and import (positive values)

**Comment by bthieurmel** [comment]
Done. For annual data and if we have only one row in selection. 

![image](https://user-images.githubusercontent.com/8750326/38558114-7413abc2-3ccf-11e8-9a4e-9062c062bdaf.png)

![image](https://user-images.githubusercontent.com/8750326/38558137-7f21af64-3ccf-11e8-9666-dc09b2025af2.png)

**Comment by jalazawa** [comment]
OK
