### ISSUE TITLE
Faire une doc sur l'installeur d'antaresVizualisation qui ... 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#151]
- explique comment mettre à jour l'installeur si on modifie un des packages 
- explique comment mettre à jour la version de R 
- explique comment mettre à jour Chrome

avoir si ce n'est pas plus pertinent de mettre la doc ici 

https://github.com/rte-antares-rpackage/antaresVizExe

OU 

Est-ce qu'un lien vers ce type de tuto suffit ? 

http://blog.skyscorer.com/2014/03/17/packaging-your-shiny-app-as-windows/

**Comment by cderv** [comment]
Si vous cherchez à packager des applications shiny sous un installateur windows, je vous conseille de regarder du coté de Rinno, c'est plutôt bien fait et récent. 
https://www.ficonsulting.com/filabs/RInno
https://github.com/ficonsulting/RInno
C'est un package R qui facilite le packaging d'une application dans un installateur avec une logique de production "professionnelle" je dirais. Intéressant quand la logique de déploiement sur serveur n'est pas possible.

**Comment by bthieurmel** [comment]
C'est ce qu'on fait "à la main" (utilisation d'inno setup). On va cependant le tester et faire la comparaison. J'ai juste un doute sur le navigateur web. De notre côté, on embarque aussi un google chrome, ce qui peut empêcher des bugs si l'utilisateur a que des navigateurs pas "top" (genre IE). A première vue, ``Rinno`` ne le propose pas encore.

**Comment by bthieurmel** [comment]
Mea culpa, on peut apparamment inclure chrome. Titouan le teste. Si cela marche bien (ce qui doit être le cas), cela sera en effet plus simple pour nous !
