### ISSUE TITLE
Cartes : problèmes de charge à régler 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#160]
les cartes sont très gourmande en mémoire et calculs côté client : 
•	pour l'animation de la carte, l'ensemble des données sont passées côté client. Si on est en horaire, ça nous donne donc 8660 * Areas * variables, et pareil pour les zones.....
•	court-terme (et ne pas avoir la page grise....) : éviter d'utiliser de l'horaire / supprimer cette option ?
•	long-terme : modifier pour envoyer les données séquentiellement au client et MAJ la carte.

**Comment by jalazawa** [comment]
Est-ce qu'on peut vérifier qu'on passe uniquement coté client les variables réellement utilisées ? (par exemple, est-ce qu'on passe Wind coté client alors que Wind n'est pas dans "color" ou "size") 

Est-ce qu'on peut aussi vérifier qu'on passe uniquement coté client les donnnées pour les zones "réels" ? (est-ce qu'on ne passe pas aussi les données des nœuds virtuels alors qu'ils ne sont pas représentés)

**Comment by bthieurmel** [comment]
Uniquement les variables nécessaires sont passées au client.

J'ai juste rajouté un filtre sur les noeuds effectivement à représenter.

**Comment by jalazawa** [comment]
OK
