### ISSUE TITLE
multiple languages : add French 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#161]
User can or cannot change the language after exploring some antares module ? 

If Yes, there is some bugs, look at the notes below. 

If Not, we must hide the flag after initialisation. 

1. Tabs are in French but module parameters are in English. 

see this picture 

![francais_parametre_requete](https://user-images.githubusercontent.com/22026724/38293960-aaa27e74-37e9-11e8-8245-9e55323e654b.png)
 
2. Legends of prodStack and plotMap are in French when I choose English 

see plotMap 
![francais_legende_plotmap](https://user-images.githubusercontent.com/22026724/38294056-f64d57c2-37e9-11e8-9390-3df6c6136b53.png)

see prodStack 
![francais_legende_prodstack](https://user-images.githubusercontent.com/22026724/38294085-0bb757e8-37ea-11e8-936f-adc1ad0ad97f.png)

3. Antares column are in English for "Chronique" when I choose French 

![francais_legende_chroniques](https://user-images.githubusercontent.com/22026724/38294168-448e2ac4-37ea-11e8-8f63-ffc242c2e18f.png)

**Comment by bthieurmel** [comment]
It's not really a bug. The change of language is effective for module for next analysis only, and we have no choice about this. (Or reset module if user change language....)

**Comment by bthieurmel** [comment]
Les modules sont ré-initialisés si la langues à changer. De plus : 
- nouveau css
- message informatif sur les drapeaux
- liens vers le github dans l'onglet à propos (et lien site antares depuis l'image).

**Comment by jalazawa** [comment]
J'ai l'impression que la carte ne fonctionne plus sur l'application via runAppAntaresViz 

J'ai du aussi installer le package geojsonlint
 
```R

 runAppAntaresViz()
Loading required package: shiny
Loading required package: manipulateWidget
Warning: package ‘manipulateWidget’ was built under R version 3.4.4
Loading required package: data.table
data.table 1.10.4.3
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com

Attaching package: ‘data.table’

The following object is masked from ‘package:raster’:

    shift


Listening on http://127.0.0.1:6569
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
Loading required namespace: rhdf5
Warning: 'geojsonlint' not installed, skipping GeoJSON linting
Warning: 'geojsonlint' not installed, skipping GeoJSON linting

```

**Comment by jalazawa** [comment]
La carte fonctionne a nouveau sur l'application : 

Les changements 

Je suis revenu à la version leaflet **1.1.0** (et j'ai laissé leaflet.minicharts 0.5.3 )

**Comment by bthieurmel** [comment]
C'est du à une mauvaise intéraction avec le petit widget développé par François qui permet de définir le layout en plaçant les points sur la carte. En effet, il utilise leaflet 0.7.7 et le plugin utilisé ne semble pas compatible avec leafet 1.x....

Solution pas simple en perspective....

**Comment by bthieurmel** [comment]
Correction proposée.

la fonction ``mapLayout`` utilisée donc directement une version de ``leaflet`` (0.7.7) et le plugin https://github.com/hiasinho/Leaflet.vector-markers. 

1- j'ai enlevé la librairie  ``leaflet` pour utiliser celle présente dans le package R
2- problème : ``Leaflet.vector-markers`` pas compatible avec les différentes versions de leaflet...
3- j'ai donc changer de plugin : https://github.com/lvoogdt/Leaflet.awesome-markers

Ca change un peu dans la forme (couleur des marqueurs paramétrables différemment) mais sinon ça fait le job.

**Comment by jalazawa** [comment]
Merci.
