### ISSUE TITLE
setProdStackAlias

### ISSUE THREAD

**Issue by IsabelleBailleul** [rte-antares-rpackage/antaresViz#180]
Cette fonction fonctionne lorsqu'on définit au moins deux "lines" :
lines = alist("Consommation" = LOAD,
                               "test" = 0),
                 lineColors = c("#a65628", "#EB9BA6")
mais ne fonctionne pas si on en définit une seule, voire pas du tout !

**Comment by pvictor** [comment]
Bonjour,

Je ne suis pas arrivé à reproduire le problème, pourriez-vous m'envoyer par mail un jeu de données et un exemple, du type : 

```r
setProdStackAlias(
  name = "Wind and solar",
  lines = alist(wind = WIND),
  lineColors = c("green")
)
prodStack(x = mydata, unit = "GWh", stack = "Wind and solar", interactive = FALSE, areas = "a")

# sauvegarde des données pour reproduire le problème
saveRDS(mydata, file = "mydata.rds")
```

Merci,

Victor
