### ISSUE TITLE
setProdStackAlias

### ISSUE THREAD

**Issue by ABurlin** [rte-antares-rpackage/antaresViz#183]
Bonjour,

Lorsque je créé un prodStack avec 3 ou 4 "lines" à l'aide de setProdStackAlias, les couleurs des lignes sur le prodStack se mélangent et ne correspondent pas à celles de la légende. Par exemple pour un prodStack avec 4 lignes sur la figure, j'ai en légende 4 couleurs: Load en marron, totalProd en rose, intercoExchanges en noir et spilled en vert foncé mais sur la figure, il y a deux lignes roses et deux lignes vertes.

N'hésitez pas à me contacter pour en discuter, je pourrais vous envoyer un exemple.

Arthur

**Comment by ABurlin** [comment]
Bonjour Victor,

Ci-joint une capture d’écran d’un prodStack avec 4 lignes :

On voit bien notamment que la ligne intercoExchanges n’est pas de la bonne couleur. Il s’agit de la ligne rose dans la partie grise du prodstack et elle est censée être en noir d’après la légende.

Merci,

Arthur
[cid:image004.jpg@01D65C32.0992E3B0]

**Comment by ABurlin** [comment]
Je ne sais pas si tu peux obtenir l'image, dans le doute je la reposte.
Il s'agit de la version 0.15.0 d'AntarezViz
<img width="943" alt="prodStack_line_error" src="https://user-images.githubusercontent.com/68422937/87775167-f0f2a380-c825-11ea-9607-b7d3a1e45526.PNG">

**Comment by pvictor** [comment]
Merci, peux-tu essayer avec la version de dev ? 

```r
devtools::install_github("rte-antares-rpackage/antaresViz")
```

Si cela ne fonctionne pas, peux-tu partager le code que tu utilises ?

Merci,

Victor

**Comment by ABurlin** [comment]
Bonjour Victor,
Désolé du délai de réponse, la partie avec devtools n'a pas fonctionnée pour moi car je ne peux pas télecharger Rtools (je n'ai pas les droits de télechargements et je ne l'ai pas trouvé sur la machine sur laquelle je travaille.)
Voici le code pour la construction du prodstack:

setProdStackAlias(
  "eco2mix2",
  variables = alist(
    "pumpedHydro" = -(pump_open + pump_closed),
    "batteryStorage" = -pump_battery,
    "import/export" = - (BALANCE + `ROW BAL.`),
    "bioenergy" = `MISC. NDG`,
    "wind" = WIND,
    "solar" = SOLAR,
    "nuclear" = NUCLEAR,
    "hydraulic" = `H. ROR` + `H. STOR` + turb_open + turb_closed,
    "gas" = GAS,
    "coal & lignite" = COAL + LIGNITE,
    "oil" = OIL,
    "smallThermal" = `MISC. DTG` + PSP,
    # PSP = autres moyens thermiques dans ces simulations
    #"other thermal" = `MIX. FUEL`,
    "Battery & DSR" = turb_battery + DSR),
  colors = c("#1147B9","#005500", "#808080", "#166A57", "#74CDB9", "#F27406", "#F5B300", "#2772B2", "#F30A0A", "#AC8C35", "#8356A2", #"#c0c0c0", 
             "#932911", "#003300"),
  lines = alist(
    "Load" = LOAD,
    "totalProd" = PSP + `MISC. NDG` + `H. ROR` + WIND + SOLAR + NUCLEAR + LIGNITE + COAL + GAS + OIL + `MIX. FUEL` + `MISC. DTG` + `H. STOR` + turb_battery + turb_open + turb_closed + DSR,
    "intercoExchanges" = - Exchanges,
    "spilled" = `SPIL. ENRG`),
  lineColors = c("#875627", "#EB9BA6", "#000000", "#005000"),
  lineWidth = 2)

Si tu as besoin que nous discutions de cela plus en détail, nous pourrons en parler. Je vais voir si je peux contourner ce problème de mon côté.

Je te remercie,

Arthur
