### ISSUE TITLE
plot : plot several curves with the same unit

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#19]
NOW, an user can plot a variable SOLAR or WIND, like this : 
![severalvariablessameunit](https://cloud.githubusercontent.com/assets/22026724/20380514/d4d52d14-aca2-11e6-8c3a-e0ddee4b19aa.png)

But maybe, he wants in the same plot SOLAR, WIND and LOAD.

**Comment by TitouanRobert** [comment]
Done

**Comment by jalazawa** [comment]
OK !
