### ISSUE TITLE
Problem with Macos -> R -> runAppAntaresViz()

### ISSUE THREAD

**Issue by thiollie** [rte-antares-rpackage/antaresViz#204]
I'm a fresh Antares User that is working on Macos. 

Tu use Antares GUI, I use a Ubuntu 22.04 on a virtualBox. It seems I coud use R/Rstudio to manage Antares input and output files, while I can run the simulation on a dedicated remote linux cluster. 

I can build simulation input from RStudio with antaresEditObject. 

But if I try to plot output, I have a problem with runAppAntaresViz(). The server is launched and the safari page is opened. But I just cannot click on the three dot button in order to open a specific path. I still have "No antares output found in directory" written because I can change the default path. 

Is there a solution for me ..? 

Thanks in advance,
Nicolas. 

Below the terminal output : 
---
> runAppAntaresViz()
Le chargement a nécessité le package : shiny
Le chargement a nécessité le package : manipulateWidget
Le chargement a nécessité le package : data.table
data.table 1.14.8 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com
**********
This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode.
This is a Mac. Please read https://mac.r-project.org/openmp/. Please engage with Apple and ask them for support. Check r-datatable.com for updates, and our Mac instructions here: https://github.com/Rdatatable/data.table/wiki/Installation. After several years of many reports of installation problems on Mac, it's time to gingerly point out that there have been no similar problems on Windows or Linux.
**********

Listening on http://127.0.0.1:5175
The `name` provided ('folder-o') does not correspond to a known icon
The `name` provided ('folder-o') does not correspond to a known icon
The `name` provided ('floppy-o') does not correspond to a known icon
Avis : `includeHTML()` was provided a `path` that appears to be a complete HTML document.
✖ Path: www/readAntares.html
ℹ Use `tags$iframe()` to include an HTML document. You can either ensure `path` is accessible in your app or document (see e.g. `shiny::addResourcePath()`) and pass the relative path to the `src` argument. Or you can read the contents of `path` and pass the contents to `srcdoc`.
Avis : `includeHTML()` was provided a `path` that appears to be a complete HTML document.
✖ Path: www/removeVirtualAreas.html
ℹ Use `tags$iframe()` to include an HTML document. You can either ensure `path` is accessible in your app or document (see e.g. `shiny::addResourcePath()`) and pass the relative path to the `src` argument. Or you can read the contents of `path` and pass the contents to `srcdoc`.
Avis : `includeHTML()` was provided a `path` that appears to be a complete HTML document.
✖ Path: www/writeAntaresH5.html
ℹ Use `tags$iframe()` to include an HTML document. You can either ensure `path` is accessible in your app or document (see e.g. `shiny::addResourcePath()`) and pass the relative path to the `src` argument. Or you can read the contents of `path` and pass the contents to `srcdoc`.

**Comment by ValentinSatge** [comment]
Hi, 
I have the same issue as Nicolas : I can't click on the 3 dots and have the same "No antares output found in directory". 
Moreover, it seems that I cannot use the "myMapLayout" function in order to create a new map. 
I am able to get that : 
![image](https://github.com/rte-antares-rpackage/antaresViz/assets/94466692/0a1e9b7c-6be2-47dc-be7a-c34dae574eff)
But I cannot do anything from there (the two buttons "set map" and "Re-init layout" seem to be out). 
I'm then struggling to create a map for my study. 
Thanks in advance,
Valentin
