### ISSUE TITLE
plot : graph with an axis X wich is not time or timeId but an another variable like LOAD or MRG. PRICE

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#21]

**Comment by TitouanRobert** [comment]
Change X-Axis on monotone curve

**Comment by TitouanRobert** [comment]
Try rbokeh, first function : bokeyHex

**Comment by jalazawa** [comment]
first remarks 

1- allow to use an antaresDataList and an antaresData 
2- allow to use this plot with interactive=FALSE 
3- launch by default a module shiny 
4- some parameters must be proposed like 

- tables : (areas, districts, links, clusters) : by default set to null 
- variable X : list of variables in tables : by default set to null : the user can choose only one variable 
- variable Y : list of variables in tables : by default set to null  : the user can choose only one variable 
- mcYear : list of mcYear in tables : by default set to null : the user can choose several mcYear 
- dateRange : by default set to the dataRange in tables : the user can choose other date in tables
- elements : set to null by default : the user can choose several elements if tables is set 

 [Use coding style like described](https://github.com/rte-antares-rpackage/antaresDev)

I will make a pull request about the last point.

**Comment by TitouanRobert** [comment]
Pour l'ajout d'infos c'est pas possible directement dans ly_hexbin, le paramètre hover ne sert pas à ça. Donc pas possible sans grosses modifications

**Comment by jalazawa** [comment]
pb avec la version interactive 

````R

pathH5<-"E:\\ANTARES\\Exemple_antares\\2_exemple_etudes_importantes\\BP_2015_2016_ConsoMedian_ex_v2\\user\\20171114-1533eco-base_30mc.h5"
> opts<-setSimulationPath(pathH5)
> plotXY(opts)

Listening on http://127.0.0.1:5624
<simpleError in charts[[chartId]]: subscript out of bounds>

```

**Comment by jalazawa** [comment]
Pour les nouvelles fonctions interactives, je propose de les préfixer par shine, shiny, module, mod ou autres. 

Les fonctions non interactives seront préfixées par plot. 

On peut changer le nom de plotXY ?

**Comment by jalazawa** [comment]
J'obtiens cette erreur pour modXY 

```R
pathH5<-"E:\\ANTARES\\Exemple_antares\\2_exemple_etudes_importantes\\BP_2015_2016_ConsoMedian_ex_v2\\user\\20171114-1533eco-base_30mc.h5"
> opts<-setSimulationPath(pathH5)
> modXY(opts)
```

Dans le viewer 

```R 
Error in xy.coords(x, y, xl, yl) : 'x' and 'y' lengths differ
```

**Comment by jalazawa** [comment]
Tjrs une erreur ...

Error in hexbin(x[ind], y[ind], shape = shape, xbins = xbins, xbnds = xbnds, : xbnds[1] < xbnds[2] is not fulfilled

**Comment by TitouanRobert** [comment]
Normal c'est les colonnes, il faut en sélectionner d'autres

**Comment by jalazawa** [comment]
YES
