### ISSUE TITLE
Proxy Configuration - hiding password

### ISSUE THREAD

**Issue by cderv** [rte-antares-rpackage/antaresViz#34]
Hi, 

To configure the proxy, we use 

```r
library(httr)
set_config(use_proxy("XXX.XXX.XX.XX", port=XXXX, username="proxy_user", password="passwd"))
```

I think the problem with that is it is not very secure because RStudio saves everything in history. So your password become accessible to anyone which can open the file `.Rhistory` or your session.

There are several solutions to that.

### Use prompt box

 Among those, RStudio has built-in fonction and an API. Normally, it is shipped by default with RStudio. Among the available functions, there is one to ask for a password `rstudioapi::askForPassword`. It opens a box for entering password and hiding what is typed. 
if `rstudioapi` package may need to be installed by the user, one could use RStudio built-in function `.rs.askForPassword` ( called by `.rs.api.askForPassword`, which is called by `rstudioapi::askForPassword`) but it is better and [advised by rstudio team](https://support.rstudio.com/hc/en-us/community/posts/200633958-Password-interaction-with-DBs-on-RStudio-Server) to use the api because it will be maintain and will continue to work even if internal design of rstudio evolves. 

So, it could be more secure to do  
````r
httr::set_config(
  httr::use_proxy("XXX.XXX.XX.XX", 
                  port=XXXX, 
                  username="proxy_user", 
                  password=rstudioapi::askForPassword("Enter a password:")
                  )
  )
````

I made some functions to do this. You can find them [here](https://gist.github.com/cderv/35b49bbe05ea6d93a2b8f2a4fe61d4b4) and you can source them directly in R with 
```r
devtools::source_gist("35b49bbe05ea6d93a2b8f2a4fe61d4b4", filename = "Config_proxy.R")
```
I plan to include them in package but it could be included in antares package too as helpers. 

### Write proxy configuration in `.Rprofile`

A solution is to put in `.Rprofile` this line to be executed when R is launched
```r
httr::set_config(httr::use_proxy("XXX.XXX.XX.XX", port=XXXX, username="proxy_user", password="passwd"))
```
However, if the `.Rprofile` is open to anyone, it is the same problem. 

### Use an identification credentials app

Make a small shiny-app or RStudio-add-in to ask for username and password and use some the encrypted package solution to secure password (`scrypt`, `digest`, `sodium`, ...). I plan to do a package to deal with proxy configuration in order to prevent users to type all that each time. Could be a more long term solution. I will keep you updated if it is any interest to your project.

### Conclusion

What do you think? 
Do you want me to update readme file to include first solution ? 
Could it be helpful to depend on another solution as workaround ?

**Comment by FrancoisGuillem** [comment]
Je ferme ce ticket car les packages sont maintenant sur le CRAN et les utilisateurs n'ont plus besoin de passer par Github pour les installer.
