### ISSUE TITLE
plotMap : color background map

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#45]
Requires rte-antares-rpackage/leaflet.minicharts#16

**Comment by FrancoisGuillem** [comment]
C'est prêt ! Pour tester il faut d'abord installer la version de développement de `leaflet.minicharts` .

Au préalable, l'utilisateur doit obtenir un fond de carte (en général au format shapefile) et l'importer dans R au format `SpatialPolygons` ou `SpatialPolygonsDataFrame` avec le package Rgdal. C'est un peu compliqué, mais pour une étude données, ce travail n'a besoin d'être réalisé qu'une seule fois. il est ensuite possible de passer cet objet à la fonction mapLayout:
```r
ml <- mapLayout(readLayout(), map = fond_de_carte) 
```
L'interface créée est légèrement différente: l'utilisateur doit alors placer les marqueurs au centre des polygones correspondants. Une fois ce travail réalisé, il peut utiliser la fonction `plotMap()` comme avant.

**Comment by jalazawa** [comment]
Génial 
![plotcartes](https://user-images.githubusercontent.com/22026724/28011209-d309a6ea-6561-11e7-9393-7895cf51ba1b.png)
!
