### ISSUE TITLE
Intégrer la possibilité de tracer simultanément le même graphe pour n simulations différentes

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#54]
Actuellement on peut comparer deux graphiques, mais il serait aussi utile de comparer n graphiques. 

Pour l'instant, cette possibilité n'est pas prévue. 

```R
#comparaison de n grpahiques 
mydata4<-readAntares(areas = "all", links = "all", clusters = "all", districts = "all" , select=c("production", "allLink"), mcYears = c(4))
mydata5<-readAntares(areas = "all", links = "all", clusters = "all", districts = "all" , select=c("production", "allLink"), mcYears = c(5))
mydata6<-readAntares(areas = "all", links = "all", clusters = "all", districts = "all" , select=c("production", "allLink"), mcYears = "all")
plot(mydata4, mydata5,mydata6)
```

**Comment by FrancoisGuillem** [comment]
C'est maintenant disponible avec la dernière version dans la branche develop.Deux syntaxes sont acceptées:

```r
plot(mydata1, mydata2) # cas où on veut comparer deux jeux de données
tsPlot(list(mydata1, mydata2, mydata3))
'''

**Comment by FrancoisGuillem** [comment]
Ces deux syntaxes sont également disponibles pour les fonction `plotMap()`, `prodStack()`, et `exchangesStack()`.

**Comment by jalazawa** [comment]
Premier problème : tsPlot ne prend pas en compte le changement de type de graphique pour toutes les instances de graphique. 

![ts_plot__bug](https://user-images.githubusercontent.com/22026724/28009145-a3018546-655a-11e7-90aa-fa0075bab7ba.png)

deuxième problème : La date ne s'affiche pas pour les deux graphiques du bas quand le type de graphique est égal à TimeSeries

**Comment by FrancoisGuillem** [comment]
La deuxième problème est lié à #85 . Je n'arrive pas à reproduire le premier. Est-ce que tu pourrais regarder si tu as des packages qui ne sont pas à jour ?

**Comment by jalazawa** [comment]
J'ai mis à jours les packages. Le premier problème a disparu. 

Mais j'ai un problème avec le type de graphique heatmap, les graphiques ne sont générés que pour la première donnée. 

![heatmap](https://user-images.githubusercontent.com/22026724/28012113-186bb4b4-6565-11e7-8939-a01c18bfbea8.png)

**Comment by FrancoisGuillem** [comment]
Ca devrait être bon maintenant.

**Comment by jalazawa** [comment]
Yes !
