### ISSUE TITLE
plot : add parameter mcYears

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#60]

**Comment by FrancoisGuillem** [comment]
When there are multiple Monte-Carlo scenarios in the data, a new control appears and lets the user choose either a synthetic chart or a chart for a specific scenario:

![image](https://cloud.githubusercontent.com/assets/3432606/24612474/a6150ce8-1885-11e7-9645-79b71ff31707.png)

**Comment by FrancoisGuillem** [comment]
A rajouter pour chaque fonction graphique.
- [x] plot
- [x] prodStack
- [x] exchangesStack
- [ ] plotMap

**Comment by FrancoisGuillem** [comment]
Le cas de plotMap est un peu plus compliqué car il faut que le filtrage des données d'entrée de la carte soit rapide pour avoir une animation fluide.

**Comment by jalazawa** [comment]
test ok
