### ISSUE TITLE
new Feature : add visualisation of input installed capacities

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresViz#69]
For a list of areas, plot a stack graph of installed thermal generation capacities.

remark : hard to do for RES (we don't have the installed capacities in ANTARES, just the time series), H. ROR and MISC. GEN.

**Comment by jalazawa** [comment]
exemple : 

```R 

 readClusterDesc()
         area               cluster      group unitcount nominalcapacity
 1:         a                  base    Lignite        44            1000
 2:         a         base_must_run    Lignite         2            1000
 3:         a                  peak        Oil        15            1000
 4:         a peak_must_run_partial        Oil         1            1000
 5:         a             semi base Mixed fuel        30            1000
 6:         b                  base    Lignite        44            1000
 7:         b                  peak        Oil        15            1000
 8:         b             semi base Mixed fuel        30            1000
 9:         c                  base    Lignite        44            1000
10:         c                  peak        Oil        15            1000
11:         c             semi base Mixed fuel        30            1000
12:         d                  base    Lignite        44            1000
13:         d                  peak        Oil        15            1000
14:         d             semi base Mixed fuel        30            1000
15:    psp in                psp_in      Other         1            6000
16:  psp in-2              psp_in_2      Other         1            3000
17:   psp out               psp_out      Other         1            6000
18: psp out-2             psp_out_2      Other         1            3000

```

Pour chaque area / group , faire la somme du produit entre unitcount et nominalcapacity , la valeur obtenue est la capacité installée par secteur. Faire une fonction qui calcul la capacité installée par secteur thermique. 

Plot : 

empiler les capacité installée par area 

X =  area 
Y = MW

**Comment by TitouanRobert** [comment]
Fait (sur la branche develop0013), j'ai aussi ajouté une fonction fans antaresProcessing qui calcul les Thermal generation (thermalGeneration(opts)) & plotThermalGeneration( thermalGeneration(opts))

**Comment by baptsegu** [comment]
Je n'arrive pas à builder le package en raison d'une dépendence à `antaresMaps` : 
`ERROR: dependency 'antaresMaps' is not available for package 'antaresViz'`

J'ai télécharger les sources d'`antaresMaps`, mais le package s'appelle en fait `spMaps`.
Bref, je suis un peu perdu

**Comment by jalazawa** [comment]
c'est normal pour l'instant, soit du fait les corrections à la main (antaresMaps --> spMaps getAntaresMap -->getSpMaps) 

Soit tu attends demain pour tester

**Comment by jalazawa** [comment]
OK
