### ISSUE TITLE
plotMap does not work with 'runtime: shiny' in Rmarkdown documents

### ISSUE THREAD

**Issue by FrancoisGuillem** [rte-antares-rpackage/antaresViz#80]

**Comment by jalazawa** [comment]
On peut mettre plusieurs applications shiny dans le document !
Test ok, avec Rmakdown/shiny/manipulateWidget/plotMap

![testplotmapshiny](https://user-images.githubusercontent.com/22026724/27227164-a21ed978-52a2-11e7-94e6-3e0e9d1afc14.png)
