### ISSUE TITLE
plotMap: controller taille minimale et maximale des étiquettes.

### ISSUE THREAD

**Issue by FrancoisGuillem** [rte-antares-rpackage/antaresViz#81]

**Comment by FrancoisGuillem** [comment]
plotMapOptions a maintenant deux nouveaux paramètres pour controller la taille des labels: `labelMinSize` et `labelMaxSize`. En utilisant la même valeur pour les deux paramètres on obtient des labels avec une taille fixe. Par exemple:

```r
plotMap(
  dataFR, ml,
  sizeAreaVars = "LOAD", 
  labelAreaVar = "MRG. PRICE",
  options = plotMapOptions(labelMaxSize = 12, labelMinSize = 12)
)
```

![image](https://cloud.githubusercontent.com/assets/3432606/26313369/fa91a078-3f0a-11e7-9ae0-b31a3bdf1161.png)

**Comment by baptsegu** [comment]
Je confirme que ça fonctionne bien.
