### ISSUE TITLE
prodStack : décalage d'une horadate entre les données et le graphique

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#84]
code R 

```R
mydata<-readAntares(areas = "all", districts = "all", links = "all", mustRun = TRUE, mcYears = 1)
prodStack(mydata$areas)

mydata$areas[area=="a" & time=="2018-01-03 20:00:00"]$LOAD
mydata$areas[area=="a" & time=="2018-01-03 19:00:00"]$LOAD
```

résultat 

```CMD
> mydata$areas[area=="a" & time=="2018-01-03 20:00:00"]$LOAD
[1] 77608
> mydata$areas[area=="a" & time=="2018-01-03 19:00:00"]$LOAD
[1] 77558
```

image 

![decalage_empilement_antaresviz](https://user-images.githubusercontent.com/22026724/27188385-471f3cb6-51ee-11e7-8ca2-2b2a68de4221.png)

**Comment by FrancoisGuillem** [comment]
Je pense que ce n'est pas un problème de prodStack mais plutôt un problème de time zone dans ton test. Les dates sont en UTC dans les `antaresDataTable`, mais quand tu crées une date implicitement elle est exprimée dans la timezone de ton ordinateur. Je pense que si tu fais:
```r
mydata$areas[area=="a" & time==as.POSIXlt("2018-01-03 19:00:00", tz = "UTC")]$LOAD
```
tu devrais obtenir 77608.
