### ISSUE TITLE
plotMapOptions() : is it possible de choose the number of decimals in the labels of plotMap()

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresViz#86]
My dear François,

Is it/could it be possible to change the number of decimals to display in the labels of plotMap ?

Thank you very much,

Baptiste

**Comment by FrancoisGuillem** [comment]
For now this is not possible. What you can do is create a new character variable with the correct number of decimals and use this new variable in parameter "label".

**Comment by TitouanRobert** [comment]
Update to respect antares rules (same operation that antaresFlowbased)
