### ISSUE TITLE
plot() : error since antaresViz 0.10

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresViz#87]
I sometimes have an error with plot() function with some combination of arguments

```
plot(data_hourly_allmc, table = "areas" ,variable = "LOAD", type = "ts", elements = "23_b", confInt = 0.95, dateRange = c("2018-01-08", "2018-01-14"), width = "100%", height = 400, interactive = FALSE)

Error in f(dt, timeStep = timeStep, variable = variable, confInt = confInt,  : 
  argument "legend" is missing, with no default
```

This error does not appear when ```interactive = TRUE```.
Moreover, this error is not solved when ```legend = TRUE ``` or ```legend = FALSE```

**Comment by FrancoisGuillem** [comment]
Ca devrait être corrigé. Tu peux tester ?

**Comment by baptsegu** [comment]
ce problème semble corrigé, mais j'ai désormais l’erreur suivante :

![image](https://user-images.githubusercontent.com/23483145/28016434-980ec8aa-6574-11e7-88d1-436defcd8d2f.png)

**Comment by jalazawa** [comment]
comme le problème initial a été résolu, je propose de clôturer ce ticket et d'ouvrir un autre ticket au sujet de plotMap. 

@baptsegu , est-ce que tu peux le faire, s'il te plait ?

**Comment by baptsegu** [comment]
Le "nouveau problème" a également été résolu en mettant à jour leaflet.minicharts (le fichier description avec la dépendance >= v0.5.0 est bien à jour et devrait éviter ce problème).

On peut cloturer l'issue.
