### ISSUE TITLE
plot : nouveau type : représenter les graphiques possibles de FactoMineR (PCA, CA, MCA etc.)

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#91]

**Comment by TitouanRobert** [comment]
Ajout de la fonction rpartPlot

**Comment by jalazawa** [comment]
Quelques remarques afin d'éviter ce type de graphique 

![initialisation](https://user-images.githubusercontent.com/22026724/33332605-fa3bb77c-d464-11e7-8a67-c91cc1ec7478.png)


Rajouter des arguments afin d'éviter ces lignes de code 

```R 
aramOptim<-c("WIND|SOLAR|LOAD|ROR|NDG|PSP|ROW|gas_ccgt_new_1|hard_coal_old_1|fr - gb")
IdMyData<-names(myDataH5Merge)[1:6]
Ids<-paste(IdMyData, sep="", collapse = "|")
IdAndVar<-paste0(list(paramOptim,Ids), sep="", collapse = "|")
NoVar<-c("NODU|FEE")
myDataH5MergeSelect<-myDataH5Merge[, .SD, .SDcols= names(myDataH5Merge) %like% IdAndVar & !names(myDataH5Merge) %like% NoVar]


res<-rpartPlot(myDataH5MergeSelect)

```


- un argument décrivant si oui ou non on souhaite prendre en compte les paramètres de la simulation 
(= données d'entrée d'ANTARES) 
Par défaut, l'argument sera égal à TRUE 

Les données d'entrées sont LOAD, WIND, SOLAR, H. ROR mais aussi les données rajoutées comme les capacités thermiques, les capacités de liens, les capacités hydrauliques etc. 

- un argument décrivant si oui ou non on souhaite garder les Id du data.Frame 
Fonction getId sur un antaresDataMerge  à faire ? comme pour un antaresData ? 
- paramètre à TRUE par défaut 

```R
dMyData
[1] "mcYear" "timeId" "time"   "day"    "month"  "hour"

```

- prendre en compte toutes les autres variables dans la fonction : par défaut à FALSE 

- un argument select comme dans getAres, getDistrict qui fait un subset sur les variables 

Par exemple, si select est égal à "fr - gb", on prendra en compte toutes les variables contenant "fr - gb". 
- cette argument est un vecteur par défaut à NULL

```R 

getAreas(select = "e")
[1] "be"        "de"        "es"        "ie"        "pompage"  
[6] "turbinage"

```

- un argument exclude
- cet argument est un vecteur par défaut à NULL

Ne pas prendre en compte une série de variable, par exemple ici, j'ai retiré "de" de ma sélection. 

```R

getAreas(select = "e", exclude = "de")
[1] "be"        "es"        "ie"        "pompage"   "turbinage"

```

Est-ce que tous ça, ça ne revient pas à faire une fonction getNames sur un antaresData ? et renvoyer le résultat à rpartPlot ? 

AUTRE remarques 

Pouvoir lancer la fonction avec interactive=FALSE pour les rapports 

Renvoyer dans tous les cas un htmlwidget dans le viewer (même comportement que les autres fonctions), exemple :

```R 

rpartPlot(myDataH5MergeSelect)

```

**Comment by jalazawa** [comment]
Rajouter un titre au graphique

**Comment by TitouanRobert** [comment]
Pour la plupart des arguments évoqués je pense qu'ils sont disponible dans readAntares. Pour moi la bonne pratique est de charger les données nécessaire à l'étude et non de charger toutes les données et de refaire une fonction qui prend les mêmes arguments que readAntares pour filtrer les données. 
Pour le nom du graphique c'est déjà possible d'en mettre un, c'est dans une des bulles de l'appli.
Pour interactive = FALSE cela nécessite que l'utilisateur fournisse déjà un objet de type rpart et non un antaresData cela est-il intéressant pour vous? Pas de problèmes au niveau technique en tout cas.

**Comment by TitouanRobert** [comment]
A faire : changer nom

**Comment by jalazawa** [comment]
Yes

**Comment by jalazawa** [comment]
Est-ce qu'on a besoin de l'algo PCA ?
