### ISSUE TITLE
plot & plotMap : légende fixe pour certaines variables 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#95]
Il faut utiliser la charte graphique pour les cartes (comme pour prodStack)

[charte graphique d'antaresViz](https://github.com/rte-antares-rpackage/antaresViz/blob/master/inst/GraphicalCharter.csv)

Par exemple, le nucléaire aura la même couleur sur un empilement de type eco2mix et sur une carte représentant des camemberts de production (nucléaire, oil, gaz etc.)

L'utilisateur pourra définir sa propre charte graphique comme pour prodStack (empilement). 

Test à faire une fois la fonctionnalité implémentée 

1.  l'ajout/la suppression de variables représentées (area, link) ne change pas la légende de la carte (sauf la ligne associée à l'ajout ou à la suppression de la variable)

2.  le changement de type de graphique (camembert, bar, polar etc.) ne change pas la légende de la carte 

3.  en général, toute modification du graphique n'entraine pas de modification de la légende

**Comment by jalazawa** [comment]
à faire d'abord pour plot puis plotMap

**Comment by TitouanRobert** [comment]
Dans plot il est possible de sélectionner plusieurs areas pour une variable. Si l'on affecte une couleur à chaque variable comment gérer le cas ou l'on à plusieurs areas?

**Comment by jalazawa** [comment]
Qu'est qui est le plus simple ? 

- Respecter la légende de prodStack pour plot uniquement pour la première area 
- Respecter la légende de prodStack uniquement si on sélectionne une area 
- autre solution ?

**Comment by TitouanRobert** [comment]
Fait en partie pour colAreaVar. De possible problèmes sur la définition des échelles (quand on à des valeurs négatives c'est très pale et quand on en à pas c'est très foncé). A discuter si c'est le comportement souhaité.

**Comment by jalazawa** [comment]
Actuellement, un problème quand on utilise la variable "Color" en premier... puis size...

**Comment by TitouanRobert** [comment]
Ajouter les couleurs sur les miniCharts

**Comment by jalazawa** [comment]
YES
