### ISSUE TITLE
plotMap : camembert avec rayon relatif

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresViz#96]
Pour l'instant tous les camemberts "Area" représentés ont la même taille, il serait intéressant de représentées de manière plus importante les camemberts "important". 

Exemple : si on représente dans des camemberts les productions nucléaire, oil, gaz et charbon des pays France, Luxembourg et Portugal alors le camembert de la France sera plus grand que celui du Portugal qui sera lui-même plus grand que celui du Luxembourg. 

La taille du camembert doit aussi varier en fonction du temps. 

Ex : si la production nucléaire, oil, gaz et charbon de la France est plus importante à 19h par rapport à 3h alors le camembert représentant la production sera plus grand à 19h. 

Formule pour calculer le rayon : 

rm = rayon minimal sur le graphique = par exemple = 0.2 (faire des tests pour avoir un nombre de pixel suffisant à représenter) (ce paramètre pourrait être modifié par l'utilisateur s'il le souhaite)

VMT = Valeur maximale de la somme des variables représentées dans le camembert pour l'espace temps T étudié pour toutes les zones

va(t, a) = Valeur de la somme des variables représentées dans le camembert à l'instant t pour la zone A

vap(t, a) = VA(t, a)/VMT = proportion de valeur de la somme de a à t par rapport aux maximum 

fM = rapport entre le rayon minimum et maximum (de préférence plus grand que un), il pourra être modifié par l'utilisateur (par défaut, on peut mettre une valeur égal à 1, 2 ou 3)

rA = rayon pour la zone A = rm(1+vap(t, a)*fM)

Exemple : cas extrêmes 

vam = minimum de la somme des variables représentées dans le camembert pour la zone A sur l'espace temporel T  

rmA = rayon minimum pour la zone A = rm(1+vam*fM)

vaM = maximum de la somme des variables représentées dans le camembert pour la zone A sur l'espace temporel T 

rMA = rayon maximum pour la zone A = rm(1+vaM*fM)

**Comment by fredbreant** [comment]
Pour la taille des camemberts entre pays, il serait peut-être judicieux d'utiliser un fonctionnement similaire à celui utilisé à l'intérieur de chaque pays avec une taille minimum et une taille maximum pour s'assurer que tous les camemberts restent lisibles (pour les plus petits) mais pas trop envahissants quand même sur la carte (pour les plus gros). 
Je ne sais pas s'il est possible de s'assurer qu'ils ne se chevauchent pas non plus.

**Comment by TitouanRobert** [comment]
Avec le rayon plus comme un effet visuel que comme un calcul exact.

**Comment by jalazawa** [comment]
Ce critère n'est pas respecté : 

rm = rayon minimal sur le graphique = par exemple = 0.2 (faire des tests pour avoir un nombre de pixel suffisant à représenter) (ce paramètre pourrait être modifié par l'utilisateur s'il le souhaite)

cf. image 


![rayonrelatif html](https://user-images.githubusercontent.com/22026724/33329682-50071c80-d45d-11e7-8c7f-bd8e336923a7.png)

**Comment by TitouanRobert** [comment]
J'ai augmenté le ratio (j'ai mis 1/6 entre le plus petit et le plus grand). Par contre pour laisser le choix à l'utilisateur du ratio il faut en discuter.

**Comment by jalazawa** [comment]
YES !
